# Generated by Django 4.1.7 on 2023-03-07 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drink',
            new_name='Todo',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='name',
            new_name='task',
        ),
    ]
